project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto
  warning: false

website:
  title: "Shuang Liang"
  favicon: static/img/favicon.drawio.svg
  site-url: https://ShuangLiang1108.github.io
  repo-url: https://github.com/ShuangLiang1108/ShuangLiang1108.github.io
  open-graph: true
  navbar:
    right:
      - text: About
        file: about/index.qmd
      - text: Research
        file: research/index.qmd
      - text: Teaching
        file: teaching/index.qmd
      - text: CV
        href: /static/cv/cv.pdf
  page-footer:
    left: |
      <span class="faux-block">{{< fa copyright >}} 2025 Shuang Liang</span>
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    center: |
      <span class="faux-block">[{{< fa brands github >}}]({{< var github-url >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">View the source at [{{< fa brands github >}} GitHub]({{< var repo-url >}})</span>
      
format:
  html:
    theme: 
      - static/html/custom.scss

bibliography: references.bib
